# Generated by Django 5.1 on 2025-09-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('Domestic Violence', 'Domestic Violence'), ('Sexual Harassment at Workplace', 'Sexual Harassment at Workplace'), ('Sexual Assault', 'Sexual Assault'), ('Dowry Harassment', 'Dowry Harassment'), ('Cyber Crime/Stalking', 'Cyber Crime/Stalking'), ('Property Dispute', 'Property Dispute'), ('Child Marriage', 'Child Marriage'), ('Other', 'Other')], max_length=50)),
                ('victim_name', models.CharField(max_length=200)),
                ('victim_age', models.IntegerField()),
                ('victim_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], default='female', max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=500)),
                ('incident_description', models.TextField()),
                ('witnesses', models.TextField(blank=True, null=True)),
                ('police_station', models.CharField(blank=True, max_length=200, null=True)),
                ('urgency', models.CharField(choices=[('low', 'Low - Not urgent'), ('medium', 'Medium - Needs attention'), ('high', 'High - Urgent'), ('emergency', 'Emergency')], default='medium', max_length=20)),
                ('previous_complaints', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('complaint_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('complaints', 'Complaints'), ('applications', 'Applications'), ('legal_claims', 'Legal Claims'), ('legal_petitions', 'Legal Petitions'), ('other', 'Other')], max_length=20)),
                ('template_content', models.TextField()),
                ('fields', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('importance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-importance', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.JSONField()),
                ('generated_content', models.TextField()),
                ('document_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documenttemplate')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
